name: expense
networks:
  default:
    name: expense
  volumes:
    mysql:
    #external :true # if true you need to to create manually
    #docker volume create mysql  
services:
  mysql:
    image: mysql:v1.0
    container_name: mysql # is equal to --name mysql
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume # -v volume-name /path/in/container
  backend: 
    image: backend:v1.0
    container_name: backend
    depends_on:
    - mysql
  frontend:
    image: frontend:v1.0
    container_name:  frontend
    depends_on:
    - backend
    ports:
    - "80:80" 
      
